export interface User {
  id: string;
  email: string;
  name: string;
  role: 'user' | 'admin';
  avatar?: string;
}

export interface Movie {
  _id: string;
  title: string;
  description: string;
  genre: string[];
  releaseYear: number;
  duration: number;
  rating: {
    average: number;
    count: number;
  };
  cast: string[];
  director: string;
  language: string;
  video: {
    url: string;
    formats: {
      quality: string;
      url: string;
      bitrate: number;
    }[];
    duration: number;
  };
  thumbnail: string;
  trailer?: {
    url: string;
    autoGenerated: boolean;
  };
  analytics: {
    viewCount: number;
  };
}

export interface Review {
  _id: string;
  userId: {
    _id: string;
    name: string;
    avatar?: string;
  };
  movieId: string;
  rating: number;
  text?: string;
  sentiment: {
    score: number;
    label: 'positive' | 'negative' | 'neutral';
  };
  createdAt: string;
  helpfulVotes: number;
}

export interface WatchHistory {
  _id: string;
  userId: string;
  movieId: Movie;
  progress: number;
  lastWatchedAt: string;
  completed: boolean;
}

export interface ApiResponse<T> {
  success: boolean;
  message?: string;
  data?: T;
}
