import mongoose, { Schema, Document } from 'mongoose';

interface SceneAnalysis {
  timestamp: number;
  duration: number;
  type: 'action' | 'dialogue' | 'emotional' | 'scenic';
  intensity: number;
  objects: string[];
  setting: string;
}

interface ContentWarning {
  type: 'violence' | 'sexual' | 'language' | 'disturbing';
  severity: 'mild' | 'moderate' | 'severe';
  timestamp: number;
  duration: number;
}

interface DetectedActor {
  name: string;
  confidence: number;
  timestamps: number[];
}

export interface IMovie extends Document {
  title: string;
  description: string;
  genre: string[];
  releaseYear: number;
  duration: number;
  rating: {
    average: number;
    count: number;
  };
  cast: string[];
  director: string;
  language: string;
  video: {
    url: string;
    formats: {
      quality: string;
      url: string;
      bitrate: number;
    }[];
    duration: number;
  };
  thumbnail: string;
  trailer?: {
    url: string;
    autoGenerated: boolean;
  };
  aiMetadata: {
    scenes: SceneAnalysis[];
    mood: string[];
    themes: string[];
    contentWarnings: ContentWarning[];
    detectedActors: DetectedActor[];
    generatedDescription: {
      vi: string;
      en: string;
    };
    embedding?: number[];
  };
  analytics: {
    viewCount: number;
    completionRate: number;
    averageWatchTime: number;
    trending: {
      score: number;
      predictedPopularity: number;
    };
  };
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const MovieSchema = new Schema<IMovie>(
  {
    title: {
      type: String,
      required: true,
      trim: true,
      index: 'text',
    },
    description: {
      type: String,
      required: true,
      index: 'text',
    },
    genre: {
      type: [String],
      required: true,
      index: true,
    },
    releaseYear: {
      type: Number,
      required: true,
      index: true,
    },
    duration: {
      type: Number,
      required: true,
    },
    rating: {
      average: {
        type: Number,
        default: 0,
        min: 0,
        max: 5,
      },
      count: {
        type: Number,
        default: 0,
      },
    },
    cast: {
      type: [String],
      default: [],
    },
    director: {
      type: String,
      default: '',
    },
    language: {
      type: String,
      default: 'en',
    },
    video: {
      url: {
        type: String,
        required: true,
      },
      formats: [
        {
          quality: String,
          url: String,
          bitrate: Number,
        },
      ],
      duration: {
        type: Number,
        required: true,
      },
    },
    thumbnail: {
      type: String,
      required: true,
    },
    trailer: {
      url: String,
      autoGenerated: {
        type: Boolean,
        default: false,
      },
    },
    aiMetadata: {
      scenes: [
        {
          timestamp: Number,
          duration: Number,
          type: {
            type: String,
            enum: ['action', 'dialogue', 'emotional', 'scenic'],
          },
          intensity: Number,
          objects: [String],
          setting: String,
        },
      ],
      mood: [String],
      themes: [String],
      contentWarnings: [
        {
          type: {
            type: String,
            enum: ['violence', 'sexual', 'language', 'disturbing'],
          },
          severity: {
            type: String,
            enum: ['mild', 'moderate', 'severe'],
          },
          timestamp: Number,
          duration: Number,
        },
      ],
      detectedActors: [
        {
          name: String,
          confidence: Number,
          timestamps: [Number],
        },
      ],
      generatedDescription: {
        vi: {
          type: String,
          default: '',
        },
        en: {
          type: String,
          default: '',
        },
      },
      embedding: [Number],
    },
    analytics: {
      viewCount: {
        type: Number,
        default: 0,
      },
      completionRate: {
        type: Number,
        default: 0,
      },
      averageWatchTime: {
        type: Number,
        default: 0,
      },
      trending: {
        score: {
          type: Number,
          default: 0,
        },
        predictedPopularity: {
          type: Number,
          default: 0,
        },
      },
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes for performance
MovieSchema.index({ title: 'text', description: 'text' });
MovieSchema.index({ genre: 1, releaseYear: -1 });
MovieSchema.index({ 'rating.average': -1 });
MovieSchema.index({ 'analytics.viewCount': -1 });
MovieSchema.index({ 'analytics.trending.score': -1 });

export const Movie = mongoose.model<IMovie>('Movie', MovieSchema);
